import { readFile, writeFile } from "node:fs/promises";

import { build } from "esbuild";

const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
const sdkPackageJson = JSON.parse(
  await readFile(new URL("../node_modules/@modelcontextprotocol/ext-apps/package.json", import.meta.url), "utf8"),
);

const result = await build({
  entryPoints: ["src/widget-app.js"],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  minify: true,
  define: {
    __MCP_APPS_SDK_VERSION__: JSON.stringify(sdkPackageJson.version),
    __REPRO_VERSION__: JSON.stringify(packageJson.version),
  },
  write: false,
});

const script = result.outputFiles[0].text.replaceAll("</script", "<\\/script");
const moduleSource =
  "// Generated by scripts/build-widget.js. Do not edit directly.\n" +
  `export const WIDGET_SCRIPT = ${JSON.stringify(script)};\n`;

await writeFile("src/widget-bundle.generated.js", moduleSource, "utf8");
