import { writeFile } from "node:fs/promises";

import { build } from "esbuild";

const result = await build({
  entryPoints: ["src/widget-app.js"],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  minify: true,
  write: false,
});

const script = result.outputFiles[0].text.replaceAll("</script", "<\\/script");
const moduleSource =
  "// Generated by scripts/build-widget.js. Do not edit directly.\n" +
  `export const WIDGET_SCRIPT = ${JSON.stringify(script)};\n`;

await writeFile("src/widget-bundle.generated.js", moduleSource, "utf8");
